definitions:
  controllers.ReqLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.ReqUser:
    properties:
      name:
        type: string
      page:
        type: integer
      pageNum:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: '{}'
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/controllers.ReqLogin'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登录
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: '{}'
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/controllers.ReqLogin'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 注册
  /api/user/userlist:
    get:
      consumes:
      - application/json
      parameters:
      - description: '{}'
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.ReqUser'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 查询用户列表
swagger: "2.0"
