xxdefinitions:
  controllers.ReqLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: '{}'
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/controllers.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登录
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: '{}'
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/controllers.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 注册
  /api/user/userlist:
    get:
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: username
        in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 查询用户列表
swagger: "2.0"
